### ISSUE TITLE
Schema issues

### ISSUE THREAD

**Issue by rglassett** [akanshmurthy/healthbook#1]
- What is a profile item? There doesn't seem to be any useful data in this table.
- Is a newsfeed item analogous to a Facebook status update? This seems like a pretty limited implementation of the newsfeed. It would be nice to display other types of updates in the feed; stuff like photos, profile updates, new friends, "Likes", etc. You'd need tables for these, of course.

**Comment by rglassett** [comment]
Shouldn't users have profile pictures (and possibly uploaded photos/albums)? Consider using something like Cloudinary for photo upload.

**Comment by rglassett** [comment]
How is patients' medical data being stored?

**Comment by rglassett** [comment]
If there's a distinction between patients and doctors, there should be a column for that (maybe `users.type`)

**Comment by rglassett** [comment]
Your timeline specifies a MedicalProfile model but I don't see a table for these.

**Comment by akanshmurthy** [comment]
In order of comments. 

I don't there needs to be a profile item. I'll change my proposal accordingly. I think there can be a Profile component with some sub-components but most of the medical profile info can either be a model by itself or be part of a user's attributes. I still need to feel this out as I develop the application. Re: newsfeed items- I responded to this in a prior issue.

As per your suggestion, I will probably use Cloudinary for that task. 

Either in its own model or as user attributes. 

Right now, I'll just focus on users.

Re: MedicalProfile model- I'm not fully sure if I should have a model for this so I'll update the proposal accordingly. 

Update: I also didn't include HIPAA compliance as part of my proposal but I would like to make the app HIPAA compliant with something like Aptible (this might be a bonus).
