### ISSUE TITLE
Search feature needs more detail

### ISSUE THREAD

**Issue by rglassett** [akanshmurthy/healthbook#4]
How will search be implemented? Will the user be searching through the text of their newsfeed items, or the entire directory of medical profiles? Think about how you will be writing your SearchBar component, as well as the SearchResults component.

**Comment by akanshmurthy** [comment]
I think ideally it would be a combination of both but, to get started, I'll focus on just the newsfeed items (which are now known as posts). I wrote a SearchBar component and placed it in the NavBar but I'm having trouble with the SearchResults (i.e. where to place it in a way that doesn't disrupt the UI).

**Comment by akanshmurthy** [comment]
I have placed the SearchResults component underneath the navbar (but as a child of the SearchBar component) with a style of position: absolute. Hopefully, this is ok and the results won't flip out if the window resizes.
